#!/bin/bash
# Periodic monitor for verlog runs. Runs `claude -p` every INTERVAL_SECONDS
# inside a long-lived tmux session on a login node.
#
# Each iteration:
#   - launches `claude -p` with monitor-settings.json (gate.sh hook routes
#     mutating tool calls to Slack for ack)
#   - posts a status message to the configured Slack channel
#
# Generic verlog scaffolding lives here. Project-agnostic Slack helpers
# live in claude-tools/slack/. User-specific paths come from monitor.env.
#
# Start:  bash monitor/launch_monitor.sh
# Attach: tmux attach -t verlog-monitor
# Stop:   tmux kill-session -t verlog-monitor

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"

# --- Load config ---
if [[ ! -r "$HERE/monitor.env" ]]; then
    echo "monitor.env not found at $HERE/monitor.env" >&2
    echo "Copy monitor.env.example to monitor.env and fill it in." >&2
    exit 1
fi
# shellcheck disable=SC1091
source "$HERE/monitor.env"

# --- Slack helper from claude-tools submodule ---
SLACK_LIB="$REPO_ROOT/claude-tools/slack/slack_post.sh"
if [[ ! -r "$SLACK_LIB" ]]; then
    echo "claude-tools submodule not initialized: $SLACK_LIB missing" >&2
    echo "Run: git submodule update --init claude-tools" >&2
    exit 1
fi
# shellcheck disable=SC1091
source "$SLACK_LIB"

# --- Required env (from monitor.env) ---
: "${CLUSTER_ID:?monitor.env must set CLUSTER_ID}"
: "${SLACK_CHANNEL_ID:?monitor.env must set SLACK_CHANNEL_ID}"
: "${SLACK_TOKEN_FILE:?monitor.env must set SLACK_TOKEN_FILE}"
: "${SMOKETEST_DIR:?monitor.env must set SMOKETEST_DIR (path to logs/ckpts root)}"
: "${WANDB_ENTITY:=}"
: "${WANDB_PROJECT:=unscripted}"
: "${WANDB_KEY_FILE:?monitor.env must set WANDB_KEY_FILE}"
: "${CONDA_ENV_PATH:?monitor.env must set CONDA_ENV_PATH}"
: "${CONDA_SH:?monitor.env must set CONDA_SH (path to conda.sh)}"
: "${USER_NAME:?monitor.env must set USER_NAME (slurm username for squeue)}"
: "${INTERVAL_SECONDS:=10800}"
: "${CLAUDE_TIMEOUT_SECONDS:=600}"

LOG_DIR="${MONITOR_LOG_DIR:-$SMOKETEST_DIR/logs/monitor}"
SUMMARY_LOG="$LOG_DIR/summary.log"
mkdir -p "$LOG_DIR"

SETTINGS_FILE="$HERE/_monitor-settings.json"  # generated by launch_monitor.sh
if [[ ! -r "$SETTINGS_FILE" ]]; then
    echo "$SETTINGS_FILE missing — run via launch_monitor.sh, not directly." >&2
    exit 1
fi

export PATH="$HOME/.local/bin:$PATH"

# Re-export so slack_post() picks them up
export SLACK_CHANNEL_ID SLACK_TOKEN_FILE SLACK_POST_LOG="$SUMMARY_LOG"

ts() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }

PROMPT="You are the periodic monitor for verlog runs on ${CLUSTER_ID}. Be terse.

Check, in order:
1. squeue -u ${USER_NAME} — list each verlog job with JOBID, NAME, PARTITION, STATE, RUNTIME.
2. ${SMOKETEST_DIR}/logs/*.events.log — show the last 5 lines of each.
3. ${SMOKETEST_DIR}/ckpts/ — list any checkpoint dirs (global_step_*).
4. wandb runs in project ${WANDB_PROJECT} under ${WANDB_ENTITY:-the active W&B entity}. To query, use this conda env + key:
   source ${CONDA_SH} && conda activate ${CONDA_ENV_PATH} && export WANDB_API_KEY=\$(cat ${WANDB_KEY_FILE}) && python3 -c \"import wandb; api=wandb.Api(); project='${WANDB_PROJECT}'; entity='${WANDB_ENTITY:-}' or api.default_entity; path=project if '/' in project else f'{entity}/{project}'; [print(r.id, r.name, r.state, r.summary.get('training/global_step','?'), r.summary.get('critic/vf_loss','?'), r.summary.get('actor/entropy','?')) for r in api.runs(path, per_page=20)]\"
5. Read ${SUMMARY_LOG} (the last ~200 lines) to see the prior iterations.

Then output (and ONLY output):
- A 1-paragraph state summary (queue + runs + ckpts).
- One short table: jobid | state | partition | runtime | wandb global_step.
- A final line beginning with \"DELTA SINCE PRIOR:\" describing what changed since the most recent prior iteration in the summary log. If first iteration, write \"DELTA SINCE PRIOR: first iteration, baseline established\".

Do NOT ask permission. Do NOT propose actions. Reporting only.

Note: any mutating action (sbatch, scancel, scontrol update) will trigger a human approval gate via Slack. You should not need to use those for read-only monitoring."

cleanup() {
    echo "[$(ts)] MONITOR_STOP pid=$$ signal=${1:-?}" >> "$SUMMARY_LOG"
    slack_post ":octagonal_sign: [${CLUSTER_ID}] monitor stopped (signal=${1:-?})" || true
    exit 0
}
trap 'cleanup TERM' TERM
trap 'cleanup INT' INT

echo "[$(ts)] MONITOR_START pid=$$ host=$(hostname) interval=${INTERVAL_SECONDS}s timeout=${CLAUDE_TIMEOUT_SECONDS}s settings=$SETTINGS_FILE" >> "$SUMMARY_LOG"
slack_post ":green_circle: [${CLUSTER_ID}] monitor started on $(hostname) — interval ${INTERVAL_SECONDS}s" || true

while true; do
    iter_ts=$(date -u +%Y%m%dT%H%M%SZ)
    iter_log="$LOG_DIR/iter-${iter_ts}.out"
    iter_start=$(date +%s)

    echo "[$(ts)] ITER_START log=$iter_log" >> "$SUMMARY_LOG"

    timeout "$CLAUDE_TIMEOUT_SECONDS" \
        claude -p "$PROMPT" \
        --permission-mode bypassPermissions \
        --allowedTools "Bash,Read,Glob,Grep" \
        --settings "$SETTINGS_FILE" \
        > "$iter_log" 2>&1
    rc=$?

    {
        echo "----- [$(ts)] iter rc=${rc} duration=$(($(date +%s) - iter_start))s file=$iter_log -----"
        cat "$iter_log" 2>/dev/null
        echo
    } >> "$SUMMARY_LOG"

    iter_end=$(date +%s)
    elapsed=$((iter_end - iter_start))

    iter_body="$(head -c 2800 "$iter_log" 2>/dev/null)"
    slack_post "*[${CLUSTER_ID}] iteration $iter_ts* (rc=${rc}, ${elapsed}s)
\`\`\`
${iter_body:-<no output>}
\`\`\`" || true

    sleep_for=$((INTERVAL_SECONDS - elapsed))
    [[ $sleep_for -lt 60 ]] && sleep_for=60
    echo "[$(ts)] ITER_END rc=${rc} elapsed=${elapsed}s next_in=${sleep_for}s" >> "$SUMMARY_LOG"
    sleep "$sleep_for"
done
